package com.jiangfeixiang.springbootblog.dao;

import com.jiangfeixiang.springbootblog.entity.ContentsDo;

import java.util.List;

/**
 * @title
 * @description contentMapper接口
 * @author jiangfeixiang
 * @updateTime
 * @throws
 */
public interface ContentsDoMapper {
    /**
     * 根据id删除
     * @param cid
     * @return
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * 插入：字段必须
     * @param record
     * @return
     */
    int insertContentsDo(ContentsDo record);

    /**
     * 插入：选择性插入
     * @param record
     * @return
     */
    int insertSelective(ContentsDo record);

    /**
     * 根据id查询
     * @param cid
     * @return
     */
    ContentsDo selectByPrimaryKey(Integer cid);

    /**
     * 选择性更新
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(ContentsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ContentsDo record);

    /**
     * 更新
     * @param record
     * @return
     */
    int updateByPrimaryKey(ContentsDo record);

    /**
     * 查询所有
     * @return
     */
    List<ContentsDo> getAllContents();
}