package com.jiangfeixiang.springbootblog.dao;

import com.jiangfeixiang.springbootblog.entity.ImagesDo;

public interface ImagesDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int insert(ImagesDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int insertSelective(ImagesDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    ImagesDo selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int updateByPrimaryKeySelective(ImagesDo paramImagesDo);

    int updateByPrimaryKey(ImagesDo paramImagesDo);

    ImagesDo selectByBlogId(Integer paramInteger);

    void deleteByBlogId(Integer paramInteger);
}