package com.jiangfeixiang.springbootblog.dao;

import com.jiangfeixiang.springbootblog.entity.ImagesDo;

public interface ImagesDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    int insert(ImagesDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    int insertSelective(ImagesDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    ImagesDo selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    int updateByPrimaryKeySelective(ImagesDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_images
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    int updateByPrimaryKey(ImagesDo record);
}