package com.jiangfeixiang.springbootblog.dao;

import com.jiangfeixiang.springbootblog.entity.LogsDo;

import java.util.List;

public interface LogsDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int insert(LogsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int insertSelective(LogsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    LogsDo selectByPrimaryKey(Integer id);

    List<LogsDo> selectAllLog();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int updateByPrimaryKeySelective(LogsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int updateByPrimaryKey(LogsDo record);
}