package com.jiangfeixiang.springbootblog.dao;

import com.jiangfeixiang.springbootblog.entity.NoticeDo;

import java.util.List;

public interface NoticeDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int insert(NoticeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int insertSelective(NoticeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    NoticeDo selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int updateByPrimaryKeySelective(NoticeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int updateByPrimaryKey(NoticeDo record);

    /**
     * 查询公告按时间倒叙
     * @return
     */
    NoticeDo selectNotice();

    /**
     * 查询所有公告
     * @return
     */
    List<NoticeDo> selectAllNotice();
}