package com.jiangfeixiang.springbootblog.dao;

import com.jiangfeixiang.springbootblog.entity.PasswordDo;

public interface PasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int insert(PasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int insertSelective(PasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    PasswordDo selectByPrimaryKey(Integer pid);

    PasswordDo selectByUserId(Integer paramInteger);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int updateByPrimaryKeySelective(PasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    int updateByPrimaryKey(PasswordDo record);
}