package com.jiangfeixiang.springbootblog.dao;

import com.jiangfeixiang.springbootblog.entity.UserDo;
import org.apache.ibatis.annotations.Param;

public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     * @mbg.generated Tue Apr 23 22:05:19 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Tue Apr 23 22:05:19 CST 2019
     */
    int insert(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Tue Apr 23 22:05:19 CST 2019
     */
    int insertSelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Tue Apr 23 22:05:19 CST 2019
     */
    UserDo selectByPrimaryKey(Integer uid);

    /**
     * 登录 根据用户名密码查询
     * @param username
     * @param password
     * @return
     */
    UserDo selectByUsernameAndPassword(@Param("username") String username,@Param("password") String password);

    /**
     * 校验用户名是否存在 根据用户名查询
     * @param username
     * @return
     */
    UserDo selectByUsername(@Param("username") String username);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Tue Apr 23 22:05:19 CST 2019
     */
    int updateByPrimaryKeySelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Tue Apr 23 22:05:19 CST 2019
     */
    int updateByPrimaryKey(UserDo record);
}