#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiangfeixiang.springbootblog.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper:
    identity: MYSQL
#设置mapper文件的位置
mybatis-plus.mapper-locations: classpath:mapper/*.xml
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#tomcat端口
server:
  port: 8080
spring:
  #数据库配置
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springboot-blog?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    name: springboot-blog
    password: 1234
    username: root

  #Redis相关配置
  redis:
    database: 0
    # 配置Redis的主机地址，需要修改成自己的
    host: 148.70.185.3
    port: 6379
    #密码没有为空即可
    password:
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
  #热部署
  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: springboot-blog/src/main
  #thymeleaf
  thymeleaf:
    mvc:
      static-path-pattern: /static/**
    prefix: classpath:/templates/
    suffix: .html
  thymeleafcache: false
  thymeleafencoding: UTF-8

  #日志记录
  logging:
    config: logback.xml
  #文件上传
  servlet:
    multipart:
      # 设置单个文件最大内存
      max-file-size: 10MB
      #设置所有文件最大内存
      max-request-size: 2048MB


