#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.jiangfeixiang.springbootblog.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper:
    identity: MYSQL

#分页
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
#tomcat端口
server:
  port: 8081
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://148.70.185.3:3306/springbootblog?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    name: springbootblog
    password: 09120127mfx521
    username: root
  #热部署
  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: springboot-blog/src/main
  #thymeleaf
  thymeleaf:
    mvc:
      static-path-pattern: /static/**
    prefix: classpath:/templates/
    suffix: .html
  thymeleafcache: false
  thymeleafencoding: UTF-8

  #日志记录
  logging:
    config: logback.xml
  #文件上传
  servlet:
    multipart:
      # 设置单个文件最大内存
      max-file-size: 10MB
      #设置所有文件最大内存
      max-request-size: 2048MB


