package com.jiangfeixiang.springbootblog.service;

import com.jiangfeixiang.springbootblog.entity.LogsDo;

/**
 * @ProjectName: springboot-blog
 * @Package: com.jiangfeixiang.springbootblog.service
 * @ClassName: LogsService
 * @Author: jiangfeixiang
 * @email: 1016767658@qq.com
 * @Description: 日志接口
 * @Date: 2019/6/12/0012 22:06
 */
public interface LogsService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Wed Jun 12 22:02:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Wed Jun 12 22:02:52 CST 2019
     */
    int insert(LogsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Wed Jun 12 22:02:52 CST 2019
     */
    int insertSelective(LogsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Wed Jun 12 22:02:52 CST 2019
     */
    LogsDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Wed Jun 12 22:02:52 CST 2019
     */
    int updateByPrimaryKeySelective(LogsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Wed Jun 12 22:02:52 CST 2019
     */
    int updateByPrimaryKey(LogsDo record);
}
