package com.jiangfeixiang.springbootblog.service;

import com.jiangfeixiang.springbootblog.entity.ReaderMassageDo;

import java.util.List;

/**
 * @ProjectName: springboot-blog
 * @Package: com.jiangfeixiang.springbootblog.service
 * @ClassName: ReaderMsgService
 * @Author: jiangfeixiang
 * @email: 1016767658@qq.com
 * @Description: 留言板接口
 * @Date: 2019/5/9/0009 13:29
 */
public interface ReaderMsgService {

    int insertSelective(ReaderMassageDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readermassage
     *
     * @mbg.generated Thu May 09 13:27:42 CST 2019
     */
    ReaderMassageDo selectByPrimaryKey(Integer id);

    /**
     * 获取所有留言信息
     * @return
     */
    List<ReaderMassageDo> getAllMsg();
}
