package com.jiangfeixiang.springbootblog.entity;

import java.io.Serializable;
import java.util.Date;

public class BlogDo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.bid
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.title
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.description
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.created
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.modified
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.author_id
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.status
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.tags
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.comments_num
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private Integer commentsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.hits
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private Integer hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.allow_comment
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private Integer allowComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogs.content
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.bid
     *
     * @return the value of t_blogs.bid
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.bid
     *
     * @param bid the value for t_blogs.bid
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.title
     *
     * @return the value of t_blogs.title
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.title
     *
     * @param title the value for t_blogs.title
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.description
     *
     * @return the value of t_blogs.description
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.description
     *
     * @param description the value for t_blogs.description
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.created
     *
     * @return the value of t_blogs.created
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.created
     *
     * @param created the value for t_blogs.created
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.modified
     *
     * @return the value of t_blogs.modified
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.modified
     *
     * @param modified the value for t_blogs.modified
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.author_id
     *
     * @return the value of t_blogs.author_id
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.author_id
     *
     * @param authorId the value for t_blogs.author_id
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.status
     *
     * @return the value of t_blogs.status
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.status
     *
     * @param status the value for t_blogs.status
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.tags
     *
     * @return the value of t_blogs.tags
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.tags
     *
     * @param tags the value for t_blogs.tags
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.comments_num
     *
     * @return the value of t_blogs.comments_num
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public Integer getCommentsNum() {
        return commentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.comments_num
     *
     * @param commentsNum the value for t_blogs.comments_num
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setCommentsNum(Integer commentsNum) {
        this.commentsNum = commentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.hits
     *
     * @return the value of t_blogs.hits
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.hits
     *
     * @param hits the value for t_blogs.hits
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.allow_comment
     *
     * @return the value of t_blogs.allow_comment
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public Integer getAllowComment() {
        return allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.allow_comment
     *
     * @param allowComment the value for t_blogs.allow_comment
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setAllowComment(Integer allowComment) {
        this.allowComment = allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogs.content
     *
     * @return the value of t_blogs.content
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogs.content
     *
     * @param content the value for t_blogs.content
     *
     * @mbg.generated Mon Aug 12 23:16:51 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}