package com.jiangfeixiang.springbootblog.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * @title
 * @description
 * @author jiangfeixiang
 * @updateTime
 * @throws
 */
public class ContentsDo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.cid
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.title
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.description
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.created
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.modified
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.author_id
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.status
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.tags
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.categories
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private String categories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.allow_comment
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private Integer allowComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contents.content
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.cid
     *
     * @return the value of t_contents.cid
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.cid
     *
     * @param cid the value for t_contents.cid
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.title
     *
     * @return the value of t_contents.title
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.title
     *
     * @param title the value for t_contents.title
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.description
     *
     * @return the value of t_contents.description
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.description
     *
     * @param description the value for t_contents.description
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.created
     *
     * @return the value of t_contents.created
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.created
     *
     * @param created the value for t_contents.created
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.modified
     *
     * @return the value of t_contents.modified
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.modified
     *
     * @param modified the value for t_contents.modified
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.author_id
     *
     * @return the value of t_contents.author_id
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.author_id
     *
     * @param authorId the value for t_contents.author_id
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.status
     *
     * @return the value of t_contents.status
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.status
     *
     * @param status the value for t_contents.status
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.tags
     *
     * @return the value of t_contents.tags
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.tags
     *
     * @param tags the value for t_contents.tags
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.categories
     *
     * @return the value of t_contents.categories
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public String getCategories() {
        return categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.categories
     *
     * @param categories the value for t_contents.categories
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setCategories(String categories) {
        this.categories = categories == null ? null : categories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.allow_comment
     *
     * @return the value of t_contents.allow_comment
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public Integer getAllowComment() {
        return allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.allow_comment
     *
     * @param allowComment the value for t_contents.allow_comment
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setAllowComment(Integer allowComment) {
        this.allowComment = allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contents.content
     *
     * @return the value of t_contents.content
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contents.content
     *
     * @param content the value for t_contents.content
     *
     * @mbg.generated Wed Apr 24 16:21:10 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}