package com.jiangfeixiang.springbootblog.entity;

public class ImagesDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.pid
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.title_Url
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    private String titleUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_images.cid
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    private Integer contentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_images.pid
     *
     * @return the value of t_images.pid
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_images.pid
     *
     * @param pid the value for t_images.pid
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_images.title_Url
     *
     * @return the value of t_images.title_Url
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    public String getTitleUrl() {
        return titleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_images.title_Url
     *
     * @param titleUrl the value for t_images.title_Url
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    public void setTitleUrl(String titleUrl) {
        this.titleUrl = titleUrl == null ? null : titleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_images.cid
     *
     * @return the value of t_images.cid
     *
     * @mbg.generated Wed Apr 24 16:13:40 CST 2019
     */
    public Integer getContentId() {
        return contentId;
    }

    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    @Override
    public String toString() {
        return "ImagesDo{" +
                "pid=" + pid +
                ", titleUrl='" + titleUrl + '\'' +
                ", contentId=" + contentId +
                '}';
    }
}