package com.jiangfeixiang.springbootblog.entity;

import java.io.Serializable;

public class PasswordDo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_password.pid
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_password.password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_password.user_id
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_password.pid
     *
     * @return the value of t_password.pid
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_password.pid
     *
     * @param pid the value for t_password.pid
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_password.password
     *
     * @return the value of t_password.password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_password.password
     *
     * @param password the value for t_password.password
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_password.user_id
     *
     * @return the value of t_password.user_id
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_password.user_id
     *
     * @param userId the value for t_password.user_id
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}