package com.jiangfeixiang.springbootblog.entity;

import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.metadata.BaseRowModel;

import java.io.Serializable;
import java.util.Date;

public class ReaderMassageDo extends BaseRowModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_readermassage.id
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    @ExcelProperty(value = {"id"}, index = 0)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_readermassage.name
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    @ExcelProperty(value = {"姓名"}, index = 1)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_readermassage.title
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    @ExcelProperty(value = {"标题"}, index = 2)
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_readermassage.content
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    @ExcelProperty(value = {"内容"}, index = 3)
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_readermassage.email
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    @ExcelProperty(value = {"邮箱"}, index = 4)
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_readermassage.created
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    @ExcelProperty(value = {"留言时间"}, index = 5)
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_readermassage.id
     *
     * @return the value of t_readermassage.id
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_readermassage.id
     *
     * @param id the value for t_readermassage.id
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_readermassage.name
     *
     * @return the value of t_readermassage.name
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_readermassage.name
     *
     * @param name the value for t_readermassage.name
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_readermassage.title
     *
     * @return the value of t_readermassage.title
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_readermassage.title
     *
     * @param title the value for t_readermassage.title
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_readermassage.content
     *
     * @return the value of t_readermassage.content
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_readermassage.content
     *
     * @param content the value for t_readermassage.content
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_readermassage.email
     *
     * @return the value of t_readermassage.email
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_readermassage.email
     *
     * @param email the value for t_readermassage.email
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_readermassage.created
     *
     * @return the value of t_readermassage.created
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_readermassage.created
     *
     * @param created the value for t_readermassage.created
     *
     * @mbg.generated Mon Aug 12 23:13:45 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}